CREATE DATABASE CARROS
GO
USE CARROS
GO
CREATE TABLE CARROS(
	id INT AUTO_INCREMENT NOT NULL,
    modelo VARCHAR(50) NOT NULL, 
    marca VARCHAR(60) NOT NULL,
    año INT(4) NOT NULL,
    color VARCHAR(20) NULL,
    CONSTRAINT PK_carros PRIMARY KEY (id)
    );
    

